repos:
- repo: local
  hooks:
  - id: checkcopyrights
    name: Copyright check
    language: system
    entry: mx python-checkcopyrights --assumed-modified --fix --files
  - id: eclipseformat
    name: Eclipse formatter
    language: system
    entry: bash scripts/pre-commit-eclipseformat.sh
