name: Weekly Downstream Tests
on:
  schedule:
  - cron: '0 0 * * 1'
  workflow_dispatch:
    inputs:
      use_ce_dev_build:
        type: boolean
        description: Use latest CE dev build for Linux and macOS instead of the standalone artifact build.
        required: false
        default: false

jobs:

  build-standalone-artifacts:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.use_ce_dev_build != true }}
    uses: ./.github/workflows/ci-matrix-gen.yml
    with:
      jobs_to_run: ^(?=.*python-svm-build-gate-linux-amd64).*$
      logs_retention_days: 0
      artifacts_retention_days: 0

  downstream-pybind11:
    needs: build-standalone-artifacts
    uses: ./.github/workflows/_downstream-test-common.yml
    with:
      package: pybind11
      needs_cmake: true
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}

  downstream-virtualenv:
    needs: build-standalone-artifacts
    uses: ./.github/workflows/_downstream-test-common.yml
    with:
      package: virtualenv
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}

  downstream-pyo3:
    needs: build-standalone-artifacts
    uses: ./.github/workflows/_downstream-test-common.yml
    with:
      package: pyo3
      needs_rust: true
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}

  downstream-pydantic-core:
    needs: build-standalone-artifacts
    uses: ./.github/workflows/_downstream-test-common.yml
    with:
      package: pydantic-core
      needs_rust: true
      needs_uv: true
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}

  downstream-jiter:
    needs: build-standalone-artifacts
    uses: ./.github/workflows/_downstream-test-common.yml
    with:
      package: jiter
      needs_rust: true
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}

  downstream-cython:
    needs: build-standalone-artifacts
    uses: ./.github/workflows/_downstream-test-common.yml
    with:
      package: cython
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}

  downstream-oracledb:
    needs:
      - build-standalone-artifacts
      - build-wheel-numpy-linux-amd64
      - build-wheel-pandas-linux-amd64
      - build-wheel-pyarrow-linux-amd64
    uses: ./.github/workflows/_downstream-test-oracledb.yml
    with:
      package: oracledb
      needs_rust: true
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}

  build-wheel-numpy-linux-amd64:
    needs: build-standalone-artifacts
    uses: ./.github/workflows/_build-wheel.yml
    with:
      package: numpy
      platform: linux
      arch: amd64
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}

  build-wheel-pandas-linux-amd64:
    needs:
      - build-standalone-artifacts
      - build-wheel-numpy-linux-amd64
    uses: ./.github/workflows/_build-wheel.yml
    with:
      package: pandas
      platform: linux
      arch: amd64
      pip_find_links_artifact: wheels-numpy-linux-amd64
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}

  build-wheel-pyarrow-linux-amd64:
    needs:
      - build-standalone-artifacts
      - build-wheel-numpy-linux-amd64
    uses: ./.github/workflows/_build-wheel.yml
    with:
      package: pyarrow
      platform: linux
      arch: amd64
      pip_find_links_artifact: wheels-numpy-linux-amd64
      use_ce_dev_build: ${{ github.event_name == 'workflow_dispatch' && inputs.use_ce_dev_build }}
